events {}

http {
    upstream auth_service {
        server auth-service:8082;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://auth_service;
        }
    }
}