server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:80
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
jwt:
  secret: your_very_long_and_secure_random_secret_key_here
management:
  endpoints:
    web:
      exposure:
        include: "*"